name: CI pipeline to lint, test, build and release code in main branch

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
    paths:
      - "src/**"
      - "test/**"
      - "package.json"
      - "tsconfig.json"
      - "vitest.config.json"
  pull_request:
    branches:
      - main
  release:
    types: [created]

permissions:
  contents: write

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm run lint

      - name: Build code
        run: pnpm run build

      - name: Run tests
        run: pnpm run test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/src/*

  build-linux:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/src/

      - name: Build Linux binary
        run: pnpm exec pkg . --targets node16-linux-x64,node16-linux-arm64 --output bin/matcha-linux

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: matcha-linux
          path: bin/*

  build-macos:
    runs-on: macos-latest
    needs: lint-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/src/

      - name: Build macOS binary
        run: pnpm exec pkg . --targets node16-macos-x64,node16-macos-arm64 --output bin/matcha-macos

      - name: Sign macOS binary
        run: |
          for file in bin/*; do
            codesign --sign - --force --deep --timestamp "$file"
          done

      - name: Upload macOS binary
        uses: actions/upload-artifact@v4
        with:
          name: matcha-macos
          path: bin/*

  build-windows:
    runs-on: windows-latest
    needs: lint-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/src/

      - name: Build Windows binary
        run: pnpm exec pkg . --targets node16-win-x64 --output bin/matcha-windows-x64

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: matcha-windows-x64
          path: bin/*

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos, build-windows]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download Linux binaries
        uses: actions/download-artifact@v4
        with:
          name: matcha-linux
          path: bin/

      - name: Download macOS binaries
        uses: actions/download-artifact@v4
        with:
          name: matcha-macos
          path: bin/

      - name: Download Windows binaries (x64 only)
        uses: actions/download-artifact@v4
        with:
          name: matcha-windows-x64
          path: bin/

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/matcha-linux-x64
            bin/matcha-linux-arm64
            bin/matcha-macos-x64
            bin/matcha-macos-arm64
            bin/matcha-windows-x64.exe
